
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package compiladores.analisadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER_DIV = 26;
  public static final int FUNCTION = 32;
  public static final int MULT = 8;
  public static final int WITH = 53;
  public static final int PACKED = 42;
  public static final int CONST = 25;
  public static final int GE = 56;
  public static final int ASSIGNMENT = 10;
  public static final int CASE = 24;
  public static final int INTEGER = 66;
  public static final int CLOSE_PARENTHESES = 16;
  public static final int REPEAT = 45;
  public static final int ARRAY = 23;
  public static final int FOR = 31;
  public static final int MINUS = 7;
  public static final int NOT = 39;
  public static final int SEMICOLON = 13;
  public static final int AND = 22;
  public static final int LT = 59;
  public static final int RECORD = 44;
  public static final int TYPE = 49;
  public static final int NIL = 38;
  public static final int OR = 41;
  public static final int IN = 35;
  public static final int OPEN_BRACKETS = 17;
  public static final int COMMA = 11;
  public static final int DIV = 9;
  public static final int BEGIN = 3;
  public static final int UQ = 55;
  public static final int UNTIL = 50;
  public static final int PLUS = 6;
  public static final int IF = 34;
  public static final int DOT = 12;
  public static final int LE = 58;
  public static final int OF = 40;
  public static final int BOOLEAN = 62;
  public static final int CRASIS = 21;
  public static final int EOF = 0;
  public static final int TRUE = 60;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 37;
  public static final int EQ = 57;
  public static final int REAL = 65;
  public static final int COLON = 14;
  public static final int CLOSE_CURLY_BRACKETS = 20;
  public static final int ELSE = 29;
  public static final int TYPE_INTEGER = 63;
  public static final int TO = 48;
  public static final int FILE = 30;
  public static final int GOTO = 33;
  public static final int WHILE = 52;
  public static final int THEN = 47;
  public static final int END = 4;
  public static final int CLOSE_BRACKETS = 18;
  public static final int STRING = 64;
  public static final int DOWNTO = 28;
  public static final int FALSE = 61;
  public static final int LABEL = 36;
  public static final int OPEN_CURLY_BRACKETS = 19;
  public static final int GT = 54;
  public static final int OPEN_PARENTHESES = 15;
  public static final int VAR = 51;
  public static final int PROCEDURE = 43;
  public static final int DO = 27;
  public static final int SET = 46;
  public static final int IDENTIFIER = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "IDENTIFIER",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGNMENT",
  "COMMA",
  "DOT",
  "SEMICOLON",
  "COLON",
  "OPEN_PARENTHESES",
  "CLOSE_PARENTHESES",
  "OPEN_BRACKETS",
  "CLOSE_BRACKETS",
  "OPEN_CURLY_BRACKETS",
  "CLOSE_CURLY_BRACKETS",
  "CRASIS",
  "AND",
  "ARRAY",
  "CASE",
  "CONST",
  "INTEGER_DIV",
  "DO",
  "DOWNTO",
  "ELSE",
  "FILE",
  "FOR",
  "FUNCTION",
  "GOTO",
  "IF",
  "IN",
  "LABEL",
  "MOD",
  "NIL",
  "NOT",
  "OF",
  "OR",
  "PACKED",
  "PROCEDURE",
  "RECORD",
  "REPEAT",
  "SET",
  "THEN",
  "TO",
  "TYPE",
  "UNTIL",
  "VAR",
  "WHILE",
  "WITH",
  "GT",
  "UQ",
  "GE",
  "EQ",
  "LE",
  "LT",
  "TRUE",
  "FALSE",
  "BOOLEAN",
  "TYPE_INTEGER",
  "STRING",
  "REAL",
  "INTEGER"
  };
}

